"""Add historical weather data table

Revision ID: add_historical_weather
Revises:
Create Date: 2025-09-28

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_historical_weather'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_mean', sa.Float(), nullable=True),
    sa.Column('precipitation_sum', sa.Float(), nullable=True),
    sa.Column('rain_sum', sa.Float(), nullable=True),
    sa.Column('snowfall_sum', sa.Float(), nullable=True),
    sa.Column('humidity_mean', sa.Float(), nullable=True),
    sa.Column('wind_speed_max', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('pressure_mean', sa.Float(), nullable=True),
    sa.Column('sunshine_duration', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('weather_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_weather_data_date'), 'historical_weather_data', ['date'], unique=True)
    op.create_index(op.f('ix_historical_weather_data_id'), 'historical_weather_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historical_weather_data_id'), table_name='historical_weather_data')
    op.drop_index(op.f('ix_historical_weather_data_date'), table_name='historical_weather_data')
    op.drop_table('historical_weather_data')
    # ### end Alembic commands ###